---
- name: Install required packages
  yum:
    name:
      - python3
      - python3-pip
      - sqlite
    state: present

- name: Install Flask via pip
  pip:
    name: flask
    executable: pip3

- name: Create app directory
  file:
    path: /opt/noteapp
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Copy Flask app to target
  copy:
    src: app.py
    dest: /opt/noteapp/app.py
    mode: '0755'

- name: Copy HTML template
  copy:
    src: index.html
    dest: /opt/noteapp/index.html
    mode: '0644'
